version: '3.8'

services:
  mongo1:
    image: mongo:6.0
    container_name: mongo1
    restart: unless-stopped
    ports:
      - "27017:27017"
    command: 
      - --replSet
      - rs0
      - --bind_ip_all
    volumes:
      - ./mongodb/data/mongo1/db:/data/db
      - ./mongodb/data/mongo1/configdb:/data/configdb
      - ./mongodb/scripts:/scripts
    healthcheck:
      test: echo 'try { db.runCommand("ping").ok } catch (e) { 0 }' | mongosh --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - mongo-cluster

  mongo2:
    image: mongo:6.0
    container_name: mongo2
    restart: unless-stopped
    ports:
      - "27018:27017"
    command: 
      - --replSet
      - rs0
      - --bind_ip_all
    volumes:
      - ./mongodb/data/mongo2/db:/data/db
      - ./mongodb/data/mongo2/configdb:/data/configdb
      - ./mongodb/scripts:/scripts
    depends_on:
      mongo1:
        condition: service_healthy
    healthcheck:
      test: echo 'try { db.runCommand("ping").ok } catch (e) { 0 }' | mongosh --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - mongo-cluster

  mongo3:
    image: mongo:6.0
    container_name: mongo3
    restart: unless-stopped
    ports:
      - "27019:27017"
    command: 
      - --replSet
      - rs0
      - --bind_ip_all
    volumes:
      - ./mongodb/data/mongo3/db:/data/db
      - ./mongodb/data/mongo3/configdb:/data/configdb
      - ./mongodb/scripts:/scripts
    depends_on:
      mongo2:
        condition: service_healthy
    healthcheck:
      test: echo 'try { db.runCommand("ping").ok } catch (e) { 0 }' | mongosh --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - mongo-cluster

  init-replica:
    image: mongo:6.0
    container_name: mongo-init
    restart: "no"
    depends_on:
      mongo1:
        condition: service_healthy
      mongo2:
        condition: service_healthy
      mongo3:
        condition: service_healthy
    volumes:
      - ./mongodb/scripts:/scripts
    command: >
      sh -c "
      echo 'Waiting for MongoDB nodes to be ready...' &&
      sleep 25 &&
      mongosh --host mongo1:27017 /scripts/replica-init.js &&
      echo 'Goida.'
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
    driver: bridge