services:
  mongodb:
    build:
      context: db
      dockerfile: Dockerfile.test
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345
      - MONGO_INITDB_DATABASE=Storage-Base
    ports:
      - "27017:27017"
    volumes:
      - ./db/data:/data/db
      - ./db/test-data:/docker-entrypoint-initdb.d
    networks:
      - app-network

  backend:
    image: maven:latest
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - ./backend:/src
      - ./mvnDeps:/root/.m2
    working_dir: /src
    networks:
      - app-network
    command: ["mvn", "spring-boot:run", "-Dspring-boot.run.jvmArguments='-Dspring.profiles.active=dev'"]

  frontend:
    image: node:latest
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - ./npmDeps:/app/node_modules
    working_dir: /app
    networks:
      - app-network
    command: ["sh", "-c", "npm run build && npm run preview -- --host 0.0.0.0 --port 3000"]

networks:
  app-network:
    driver: bridge